OOP 03
hobathanh/JavaExercise pull request #36
Opened 2023-02-16 07:40 UTC by hobathanh

2023-02-20 02:24 UTC, nguyenvanman requested changes

2023-02-20 02:24 UTC, nguyenvanman commented on src/main/java/com/bathanh/exercise/oop/oop3/Student.java
> +    private final LocalDate birthDay;
```suggestion
    private final LocalDate birthday;
```

2023-02-20 02:49 UTC, voquanghoa approved these changes

2023-02-21 04:54 UTC, hobathanh commented on src/main/java/com/bathanh/exercise/oop/oop3/Student.java
> +    private final LocalDate birthDay;
resolved

2023-02-21 06:28 UTC, merged